# Generated by Django 4.1.4 on 2023-01-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='dafault', max_length=63)),
                ('categorie', models.CharField(default='dafault', max_length=31)),
                ('type', models.CharField(default='dafault', max_length=31)),
                ('surface', models.CharField(default='dafault', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.CharField(default='dafault', max_length=31)),
                ('annonceurid', models.CharField(default='dafault', max_length=31)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=31)),
                ('commune', models.CharField(max_length=31)),
                ('latitude', models.CharField(max_length=31)),
                ('longitude', models.CharField(max_length=31)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=31)),
                ('prenom', models.CharField(blank=True, max_length=31, null=True)),
                ('email', models.CharField(blank=True, max_length=31, null=True)),
                ('adresseannonceur', models.CharField(blank=True, max_length=31, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.annonce')),
            ],
        ),
    ]
