# Generated by Django 4.1.4 on 2023-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_annonce_localisation_image_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='annonceurid',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='latitude',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='longitude',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
