# Generated by Django 4.1.4 on 2023-01-05 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_lien_alter_annonce_annonceurid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
