# Generated by Django 4.1.4 on 2023-01-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_annonce_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['date']},
        ),
    ]
