# Generated by Django 4.1.4 on 2023-01-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_annonce_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='ka_beraoud@esi.dz', max_length=255)),
                ('isadmin', models.BooleanField(default=False)),
                ('username', models.CharField(default='user', max_length=63)),
            ],
        ),
        migrations.DeleteModel(
            name='Superuser',
        ),
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='annonceurid',
        ),
        migrations.AddField(
            model_name='annonce',
            name='annonceuremail',
            field=models.CharField(blank=True, default='default', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
    ]
