# Generated by Django 4.1.4 on 2023-01-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_utilisateur_delete_superuser_alter_annonce_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='utilisateur',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
    ]
